"""PettingZoo ParallelEnv wrapping SUMO taxi-dispatch via TraCI.

Per-taxi action: Discrete(K+1)
  - 0 = no-op (idle taxi keeps randomCircling)
  - 1..K = accept the k-th nearest pending reservation

Per-taxi observation (Dict):
  - self:               [x_norm, y_norm, active_time_norm]
  - neighbor_taxis:     (K, 4)   [dx, dy, is_empty, dist_norm]
  - neighbor_taxis_mask:(K,)     1 = valid
  - reservations:       (K, 5)   [dx_pu, dy_pu, dx_do, dy_do, wait_norm]
  - reservations_mask:  (K,)     1 = valid
  - position_valid:     (1,)     1 = trustworthy, 0 = degraded

Reward is a team scalar broadcast to every acting agent. Global step metrics
remain available even when no taxi can act:
  R = completed_journeys_this_step − λ · mean_current_wait_time

Episode ends when SUMO reaches the sumocfg <time><end/> value.

Only ONE DispatchEnv per Python process — TraCI is single-connection.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
from gymnasium import spaces
from pettingzoo import ParallelEnv

from ._sumo import traci  # libsumo if available, else traci
import sumolib  # noqa: E402

from .degradation import DegradationConfig, DegradationLayer
from .scenario import Scenario, load_scenario


# Observation feature widths — kept in module-level constants so the GAT
# encoder later can import the same numbers.
#
# Self feature layout:
#   [x_norm, y_norm, episode_time_norm, velocity_norm, aoi_norm]
# where velocity_norm is speed / 30 m/s (~108 km/h) clipped to [0, 1], and
# aoi_norm is Age of Information / AOI_MAX_S clipped to [0, 1].
SELF_FEAT_DIM = 5
# Neighbour-taxi features: [dx, dy, is_empty, dist_norm, aoi_norm]. AoI was
# added to expose per-node staleness for the WAMSN metric (§7.4). Neighbours'
# AoI is refreshed every sim step by the DegradationLayer, whether or not
# the neighbour happens to be the acting agent.
TAXI_FEAT_DIM = 5
RES_FEAT_DIM = 5

# Normalisation constants used by the observation builder. Set explicitly here
# so the policy and any future faithfulness code can import them.
VELOCITY_MAX_MS = 30.0
# A 60 s stale observation maps to 1.0 for the reported outage-duration range.
AOI_MAX_S = 60.0


@dataclass(frozen=True)
class StepMetrics:
    """Environment-wide outcomes from one RL step.

    These values do not depend on the set of taxis that happened to be able to
    act. Consumers should read ``env.last_step_metrics`` instead of selecting
    an arbitrary entry from the per-agent ``infos`` dictionary.
    """

    completed_passenger_journeys: int = 0
    accepted_dispatches: int = 0
    mean_pending_wait_s: float = 0.0
    team_reward: float = 0.0
    sim_time_s: float = 0.0
    accepted_dispatch_agents: tuple[str, ...] = ()
    terminated: bool = False
    sumo_died: bool = False


@dataclass
class DispatchEnvConfig:
    area: str = "central_park"
    n_taxis: int = 20
    k_neighbors: int = 5
    k_reservations: int = 5
    step_length_s: int = 10  # SUMO seconds advanced per RL step
    # Reward = pickup_reward * completed_passenger_journeys_this_step
    #        + dispatch_reward * successful_dispatches_this_step
    #        - wait_penalty_lambda * mean_pending_wait_time_s
    # Defaults intentionally give large weight to completed journeys so the
    # policy can't degenerate into "do nothing to avoid the wait penalty".
    pickup_reward: float = 10.0
    dispatch_reward: float = 0.5
    # Actor-only difference credit. Team reward reporting remains unchanged;
    # the agent whose dispatch succeeds receives this additional training cue.
    dispatch_credit_reward: float = 0.5
    wait_penalty_lambda: float = 0.001
    seed: int = 42
    degradation: DegradationConfig = field(default_factory=DegradationConfig)
    # Attention-drift measurement (§7.4): when True, every obs build also
    # produces the *clean* counterfactual of the same observation — what the
    # agent would have seen with degradation off (true position/velocity,
    # AoI = 0, position_valid = 1). Exposed via `env.last_clean_obs`, keyed
    # like the returned obs dict. Because the degradation layer only mutates
    # observations (never simulator state), the clean twin is exact — no
    # paired-episode machinery needed. Costs one extra feature-array build
    # per agent per step; leave False for training.
    emit_clean_obs: bool = False
    # Rider-demand variant (E-section protocol, proposal §7.6). Name of a
    # `<area>_taxis_vNNN.rou.xml` generated by
    # `scripts/add_taxis.py --variants N`. When set, reset() overrides the
    # sumocfg's route files with (background traffic, this variant) via
    # SUMO's --route-files flag — the committed sumocfg is never touched.
    # Can also be swapped per episode: reset(options={"taxi_route_file": ...}).
    taxi_route_file: str | None = None
    # For debugging / smoke tests. Never set True in a training run.
    use_gui: bool = False


class DispatchEnv(ParallelEnv):
    metadata = {"name": "dispatch_marl_v0", "is_parallelizable": False}

    def __init__(self, config: DispatchEnvConfig | None = None):
        super().__init__()
        self.config = config or DispatchEnvConfig()
        self.scenario: Scenario = load_scenario(self.config.area)
        self.possible_agents: list[str] = [
            f"taxi_{i}" for i in range(self.config.n_taxis)
        ]
        self.agents: list[str] = []
        # Per-agent cache of the reservation-ID ordering presented at observation time,
        # so an action index in {1..K} can be translated back to a concrete
        # reservation ID at step time.
        self._pending_res_map: dict[str, list[str]] = {}
        # Clean counterfactual of the latest obs build (emit_clean_obs only).
        self._last_clean_obs: dict[str, dict[str, np.ndarray]] = {}
        # Bookkeeping.
        self._sumo_started = False
        self._sumo_label: str | None = None  # unique TraCI connection label
        self._label_counter = 0
        self._sim_time = 0.0
        self._end_time = 0.0
        self._last_step_metrics = StepMetrics()
        self._net_bbox = (0.0, 0.0, 1.0, 1.0)  # xmin, ymin, xmax, ymax
        self._net_diag = 1.0
        self._rng = np.random.default_rng(self.config.seed)
        self._degradation = DegradationLayer(
            self.config.degradation, self.scenario.tunnel_edges, self._rng
        )
        # Pre-build gymnasium spaces so PettingZoo can query them.
        self._obs_space = self._make_obs_space()
        self._act_space = spaces.Discrete(self.config.k_reservations + 1)

    # ------------------------------------------------------------------ spaces

    def _make_obs_space(self) -> spaces.Dict:
        K_n = self.config.k_neighbors
        K_r = self.config.k_reservations
        return spaces.Dict({
            "self": spaces.Box(-np.inf, np.inf, shape=(SELF_FEAT_DIM,), dtype=np.float32),
            "neighbor_taxis": spaces.Box(-np.inf, np.inf, shape=(K_n, TAXI_FEAT_DIM), dtype=np.float32),
            "neighbor_taxis_mask": spaces.Box(0, 1, shape=(K_n,), dtype=np.int8),
            "reservations": spaces.Box(-np.inf, np.inf, shape=(K_r, RES_FEAT_DIM), dtype=np.float32),
            "reservations_mask": spaces.Box(0, 1, shape=(K_r,), dtype=np.int8),
            "position_valid": spaces.Box(0, 1, shape=(1,), dtype=np.int8),
        })

    def observation_space(self, agent: str) -> spaces.Space:
        return self._obs_space

    def action_space(self, agent: str) -> spaces.Space:
        return self._act_space

    # ------------------------------------------------------------------ reset

    def reset(self, seed: int | None = None, options: dict | None = None):
        if seed is not None:
            self.config = DispatchEnvConfig(**{**self.config.__dict__, "seed": seed})
            self._rng = np.random.default_rng(seed)
            self._degradation = DegradationLayer(
                self.config.degradation, self.scenario.tunnel_edges, self._rng
            )
        # Always clear per-agent AoI state; a fresh episode starts every taxi
        # with no history of trusted readings.
        self._degradation.reset()

        # Prefer traci.load() to restart the same SUMO subprocess between
        # episodes — avoids process-startup overhead AND avoids the "label
        # already active" registry collision that plagues close+start.
        load_args = [
            "-c", str(self.scenario.sumocfg),
            "--no-step-log",
            "--no-warnings",
        ]
        # Rider-demand variant override (per-episode option wins over config).
        taxi_route = self.config.taxi_route_file
        if options and "taxi_route_file" in options:
            taxi_route = options["taxi_route_file"]
        if taxi_route:
            scen_dir = self.scenario.sumocfg.parent
            variant = Path(taxi_route)
            if not variant.is_absolute():
                variant = scen_dir / variant
            if not variant.exists():
                raise FileNotFoundError(
                    f"demand variant not found: {variant} — generate with "
                    f"`python scripts/add_taxis.py --area {self.scenario.name} --variants N`"
                )
            background = scen_dir / f"{self.scenario.name}.rou.xml"
            # Command-line --route-files takes precedence over the sumocfg's
            # <route-files>; paths are absolute so cwd doesn't matter.
            load_args += ["--route-files", f"{background},{variant}"]
        reloaded = False
        if self._sumo_started and self._sumo_label is not None:
            try:
                traci.switch(self._sumo_label)
                traci.load(load_args)
                reloaded = True
            except (traci.exceptions.TraCIException, traci.exceptions.FatalTraCIError):
                try:
                    traci.close()
                except (traci.exceptions.TraCIException, traci.exceptions.FatalTraCIError):
                    pass
                self._sumo_started = False

        if not reloaded:
            # Fresh SUMO subprocess with a unique label to prevent
            # collide with a stale "default" entry left by a prior fatal.
            self._label_counter += 1
            self._sumo_label = f"env_{id(self):x}_{self._label_counter}"
            binary = sumolib.checkBinary("sumo-gui" if self.config.use_gui else "sumo")
            traci.start([binary, *load_args], label=self._sumo_label)
            traci.switch(self._sumo_label)
            self._sumo_started = True

        # Cache global bounds for observation normalisation.
        # getNetBoundary returns ((xmin, ymin), (xmax, ymax)).
        (xmin, ymin), (xmax, ymax) = traci.simulation.getNetBoundary()
        self._net_bbox = (xmin, ymin, xmax, ymax)
        self._net_diag = max(1.0, float(np.hypot(xmax - xmin, ymax - ymin)))
        self._end_time = float(traci.simulation.getEndTime())

        # Step until at least one taxi is alive (they spawn at t=0 but SUMO
        # inserts after the first step).
        for _ in range(2):
            traci.simulationStep()
        self._sim_time = traci.simulation.getTime()
        self._last_step_metrics = StepMetrics(sim_time_s=self._sim_time)

        self.agents = self._active_idle_taxi_ids()
        obs = self._build_all_obs(self.agents)
        infos = {a: {} for a in self.agents}
        return obs, infos

    # ------------------------------------------------------------------ step

    def step(self, actions: dict[str, int]):
        try:
            return self._step_impl(actions)
        except traci.exceptions.FatalTraCIError:
            # SUMO died. Force clean episode termination so the RL loop
            # doesn't need to unwind an exception.
            self._sim_time = self._end_time
            self._sumo_started = False
            self._last_step_metrics = StepMetrics(
                sim_time_s=self._sim_time,
                terminated=True,
                sumo_died=True,
            )
            return {}, {a: 0.0 for a in actions}, {a: True for a in actions}, \
                {a: False for a in actions}, {a: {"sumo_died": True} for a in actions}

    def _step_impl(self, actions: dict[str, int]):
        # 1. Apply dispatch actions before advancing the sim. Cross-check each
        #    (agent, reservation) against SUMO's *current* state before calling
        #    dispatchTaxi — the reservation must still exist, and the taxi must
        #    still be idle. Random-init policies often violate both, and while
        #    a mismatch used to be handled by SUMO with a soft error, in
        #    recent versions it can close the TraCI connection outright.
        try:
            live_idle = set(traci.vehicle.getTaxiFleet(0))
            live_res_ids = {r.id for r in traci.person.getTaxiReservations(0)}
        except traci.exceptions.TraCIException:
            live_idle = set()
            live_res_ids = set()

        pickups_dispatched: list[str] = []  # assigned reservation IDs
        successful_dispatch_agents: set[str] = set()
        for agent, action in actions.items():
            if action == 0 or agent not in live_idle:
                continue
            candidates = self._pending_res_map.get(agent, [])
            k_idx = int(action) - 1
            if k_idx < 0 or k_idx >= len(candidates):
                continue
            res_id = candidates[k_idx]
            if res_id in pickups_dispatched or res_id not in live_res_ids:
                continue
            try:
                traci.vehicle.dispatchTaxi(agent, [res_id])
                pickups_dispatched.append(res_id)
                successful_dispatch_agents.add(agent)
            except traci.exceptions.TraCIException:
                continue

        # 2. Advance the simulation by step_length_s SUMO seconds. SUMO's
        #    arrived-person event means that a rider reached their destination;
        #    it is not a passenger-pickup event.
        completed_journeys_delta = 0
        target = self._sim_time + self.config.step_length_s
        while self._sim_time < target and self._sim_time < self._end_time:
            traci.simulationStep()
            completed_journeys_delta += len(
                traci.simulation.getArrivedPersonIDList()
            )
            self._sim_time = traci.simulation.getTime()

        # 3. Build reward.
        n_dispatches_ok = len(pickups_dispatched)
        mean_wait = self._mean_pending_wait_time()
        shared_task_reward = (
            self.config.pickup_reward * float(completed_journeys_delta)
            - self.config.wait_penalty_lambda * mean_wait
        )
        team_r = (
            shared_task_reward
            + self.config.dispatch_reward * float(n_dispatches_ok)
        )

        # 4. Decide termination and next agent set.
        terminated_all = self._sim_time >= self._end_time
        self.agents = [] if terminated_all else self._active_idle_taxi_ids()

        self._last_step_metrics = StepMetrics(
            completed_passenger_journeys=completed_journeys_delta,
            accepted_dispatches=n_dispatches_ok,
            mean_pending_wait_s=mean_wait,
            team_reward=team_r,
            sim_time_s=self._sim_time,
            accepted_dispatch_agents=tuple(sorted(successful_dispatch_agents)),
            terminated=terminated_all,
        )

        obs = self._build_all_obs(self.agents)
        rewards = {a: team_r for a in actions}
        # For dead / newly-inactive agents that had actions this step, still
        # report the (final) reward with a terminated=True flag.
        terminations = {a: terminated_all for a in actions}
        truncations = {a: False for a in actions}
        infos = {
            a: {
                "completed_passenger_journeys_delta": completed_journeys_delta,
                # Protocol-v1 compatibility alias. This value counts completed
                # journeys, despite the historical field name.
                "pickups_delta": completed_journeys_delta,
                "dispatches_ok": n_dispatches_ok,
                "mean_wait_time": mean_wait,
                "sim_time": self._sim_time,
                "team_reward": team_r,
                # Preserve the reported team reward, then add an actor-only
                # difference credit for the taxi whose dispatch was accepted.
                "training_reward": (
                    team_r
                    + self.config.dispatch_credit_reward
                    * float(a in successful_dispatch_agents)
                ),
            }
            for a in actions
        }
        return obs, rewards, terminations, truncations, infos

    @property
    def last_step_metrics(self) -> StepMetrics:
        """Environment-wide outcomes from the most recently completed step."""
        return self._last_step_metrics

    @property
    def done(self) -> bool:
        """True when the episode can no longer be stepped meaningfully.

        Two paths get us here: (a) SUMO reached its configured end_time,
        or (b) SUMO died mid-episode (`_sumo_started` was flipped to False
        by the fatal-error handler). Either way, the training loop should
        stop stepping and move on to the next epoch.
        """
        if not self._sumo_started:
            return True
        return self._sim_time >= self._end_time

    @property
    def sim_time(self) -> float:
        return self._sim_time

    @property
    def last_clean_obs(self) -> dict[str, dict[str, np.ndarray]]:
        """Clean counterfactuals of the most recent obs build.

        Only populated when `config.emit_clean_obs` is True; keys mirror the
        obs dict returned by the same reset()/step() call. Used by the
        attention-drift evaluation: forward the degraded obs and its clean
        twin through the policy and compare attention rows.
        """
        return self._last_clean_obs

    def close(self) -> None:
        if self._sumo_started:
            try:
                if self._sumo_label is not None:
                    traci.switch(self._sumo_label)
                traci.close()
            except (traci.exceptions.FatalTraCIError, traci.exceptions.TraCIException):
                pass
            self._sumo_started = False
            self._sumo_label = None

    # ------------------------------------------------------------------ helpers

    def _active_idle_taxi_ids(self) -> list[str]:
        """Return only taxis that are (a) alive in the sim and (b) idle."""
        try:
            alive = set(traci.vehicle.getIDList())
            idle = set(traci.vehicle.getTaxiFleet(0))
        except traci.exceptions.TraCIException:
            return []
        return sorted(
            a for a in self.possible_agents if a in alive and a in idle
        )

    def _mean_pending_wait_time(self) -> float:
        reservations = traci.person.getTaxiReservations(0)
        if not reservations:
            return 0.0
        now = self._sim_time
        waits = [max(0.0, now - r.reservationTime) for r in reservations]
        return float(np.mean(waits))

    # -------------------------------------------------------------- observations

    def _build_all_obs(self, agents: list[str]) -> dict[str, dict[str, np.ndarray]]:
        self._last_clean_obs = {}
        if not agents:
            self._pending_res_map = {}
            return {}
        # One shared telemetry table per step (proposal §7.2): each taxi's
        # reading is produced ONCE by the degradation layer and every
        # observer — the taxi itself and all peers — sees the same, possibly
        # frozen, last-known state. `true_state` is kept alongside for the
        # exact clean twin (emit_clean_obs).
        try:
            alive = set(traci.vehicle.getIDList())
            empty_ids = set(traci.vehicle.getTaxiFleet(0))
            reservations = list(traci.person.getTaxiReservations(0))
            observed: dict[str, tuple[float, float, float, bool, float]] = {}
            true_state: dict[str, tuple[float, float, float]] = {}
            for taxi_id in [a for a in self.possible_agents if a in alive]:
                x_t, y_t = traci.vehicle.getPosition(taxi_id)
                try:
                    v_t = float(traci.vehicle.getSpeed(taxi_id))
                except traci.exceptions.TraCIException:
                    v_t = 0.0
                edge = traci.vehicle.getRoadID(taxi_id)
                true_state[taxi_id] = (x_t, y_t, v_t)
                observed[taxi_id] = self._degradation.observe(
                    taxi_id, x_t, y_t, v_t, edge, self._sim_time
                )
        except traci.exceptions.TraCIException:
            return {a: self._empty_obs() for a in agents}

        obs = {}
        for agent in agents:
            obs[agent] = self._build_agent_obs(
                agent, observed, true_state, empty_ids, reservations
            )
        return obs

    def _empty_obs(self) -> dict[str, np.ndarray]:
        K_n = self.config.k_neighbors
        K_r = self.config.k_reservations
        return {
            "self": np.zeros(SELF_FEAT_DIM, dtype=np.float32),
            "neighbor_taxis": np.zeros((K_n, TAXI_FEAT_DIM), dtype=np.float32),
            "neighbor_taxis_mask": np.zeros(K_n, dtype=np.int8),
            "reservations": np.zeros((K_r, RES_FEAT_DIM), dtype=np.float32),
            "reservations_mask": np.zeros(K_r, dtype=np.int8),
            "position_valid": np.zeros(1, dtype=np.int8),
        }

    def _build_agent_obs(
        self,
        agent: str,
        observed: dict[str, tuple[float, float, float, bool, float]],
        true_state: dict[str, tuple[float, float, float]],
        empty_ids: set[str],
        reservations: list[Any],
    ) -> dict[str, np.ndarray]:
        """Build one agent's obs from the shared observed-telemetry table.

        All geometry — self position, neighbour relative vectors, neighbour
        ordering, reservation relative vectors and ordering — is computed
        from the *observed* (possibly frozen) states: the agent plans on
        the last-known world, exactly as a real dispatch platform would.

        When emit_clean_obs is on, a clean twin is built over the SAME
        entities in the SAME slots (so per-slot attention comparison is
        well-defined) with features from the true state and AoI = 0.
        """
        if agent not in observed:
            return self._empty_obs()

        x, y, v, degraded, aoi = observed[agent]
        x_true, y_true, v_true = true_state[agent]
        emit_clean = self.config.emit_clean_obs
        time_norm = min(1.0, self._sim_time / max(1.0, self._end_time))

        def _self_feat(sx, sy, sv, saoi):
            return np.array([
                self._norm_x(sx),
                self._norm_y(sy),
                time_norm,
                min(1.0, max(0.0, sv) / VELOCITY_MAX_MS),
                min(1.0, saoi / AOI_MAX_S),
            ], dtype=np.float32)

        self_feat = _self_feat(x, y, v, aoi)

        # ------------- neighbouring taxis (observed geometry) -------------
        K_n = self.config.k_neighbors
        others = [(oid, s[0], s[1], s[4]) for oid, s in observed.items() if oid != agent]
        others.sort(key=lambda t: (t[1] - x) ** 2 + (t[2] - y) ** 2)
        chosen = others[:K_n]
        taxi_feat = np.zeros((K_n, TAXI_FEAT_DIM), dtype=np.float32)
        taxi_mask = np.zeros(K_n, dtype=np.int8)
        for i, (oid, ox, oy, oaoi) in enumerate(chosen):
            dx, dy = ox - x, oy - y
            taxi_feat[i] = [
                dx / self._net_diag,
                dy / self._net_diag,
                1.0 if oid in empty_ids else 0.0,
                float(np.hypot(dx, dy)) / self._net_diag,
                min(1.0, oaoi / AOI_MAX_S),
            ]
            taxi_mask[i] = 1

        # ------------- pending reservations (relative to observed self) ---
        K_r = self.config.k_reservations
        res_with_coords = []
        for r in reservations:
            try:
                px, py = traci.simulation.convert2D(r.fromEdge, 0.0, laneIndex=0)
                res_with_coords.append((r, px, py, float(np.hypot(px - x, py - y))))
            except traci.exceptions.TraCIException:
                continue
        res_with_coords.sort(key=lambda t: t[3])
        chosen_res = res_with_coords[:K_r]

        res_feat = np.zeros((K_r, RES_FEAT_DIM), dtype=np.float32)
        res_mask = np.zeros(K_r, dtype=np.int8)
        res_ids: list[str] = []
        res_coords: list[tuple[float, float, float, float]] = []
        for i, (r, px, py, _) in enumerate(chosen_res):
            try:
                qx, qy = traci.simulation.convert2D(r.toEdge, 0.0, laneIndex=0)
            except traci.exceptions.TraCIException:
                qx, qy = px, py
            wait = max(0.0, self._sim_time - r.reservationTime)
            res_feat[i] = [
                (px - x) / self._net_diag,
                (py - y) / self._net_diag,
                (qx - x) / self._net_diag,
                (qy - y) / self._net_diag,
                min(1.0, wait / 600.0),
            ]
            res_mask[i] = 1
            res_ids.append(r.id)
            res_coords.append((px, py, qx, qy))
        self._pending_res_map[agent] = res_ids

        obs = {
            "self": self_feat,
            "neighbor_taxis": taxi_feat,
            "neighbor_taxis_mask": taxi_mask,
            "reservations": res_feat,
            "reservations_mask": res_mask,
            "position_valid": np.array([0 if degraded else 1], dtype=np.int8),
        }

        if emit_clean:
            # Clean twin: same node identities per slot, features from the
            # TRUE state with AoI = 0 everywhere. Both the self node and
            # every neighbour un-freeze; reservation vectors re-anchor to
            # the true self position (order data itself is never degraded).
            clean_self = _self_feat(x_true, y_true, v_true, 0.0)
            clean_taxis = np.zeros((K_n, TAXI_FEAT_DIM), dtype=np.float32)
            for i, (oid, _, _, _) in enumerate(chosen):
                tx, ty, _tv = true_state.get(oid, (0.0, 0.0, 0.0))
                dx, dy = tx - x_true, ty - y_true
                clean_taxis[i] = [
                    dx / self._net_diag,
                    dy / self._net_diag,
                    taxi_feat[i][2],
                    float(np.hypot(dx, dy)) / self._net_diag,
                    0.0,
                ]
            clean_res = np.zeros((K_r, RES_FEAT_DIM), dtype=np.float32)
            for i, (px, py, qx, qy) in enumerate(res_coords):
                clean_res[i] = [
                    (px - x_true) / self._net_diag,
                    (py - y_true) / self._net_diag,
                    (qx - x_true) / self._net_diag,
                    (qy - y_true) / self._net_diag,
                    res_feat[i][4],
                ]
            self._last_clean_obs[agent] = {
                "self": clean_self,
                "neighbor_taxis": clean_taxis,
                "neighbor_taxis_mask": taxi_mask.copy(),
                "reservations": clean_res,
                "reservations_mask": res_mask.copy(),
                "position_valid": np.ones(1, dtype=np.int8),
            }

        return obs

    def _norm_x(self, x: float) -> float:
        return (x - self._net_bbox[0]) / max(1.0, self._net_bbox[2] - self._net_bbox[0])

    def _norm_y(self, y: float) -> float:
        return (y - self._net_bbox[1]) / max(1.0, self._net_bbox[3] - self._net_bbox[1])
